### ISSUE TITLE
Thank you for the program and the data from VirusTotal

### ISSUE THREAD

**Issue by mrkaban** [taskexplorer/TaskExplorer#11]
Thanks for the rather powerful replacement of the Windows task manager, and even under the GNU GPL license, I added the program to my site ([link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D1%83%D1%82%D0%B8%D0%BB%D0%B8%D1%82%D1%8B/%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0/taskexplorer-%D0%B4%D0%B8%D1%81%D0%BF%D0%B5%D1%82%D1%87%D0%B5%D1%80-%D0%B7%D0%B0%D0%B4%D0%B0%D1%87-windows.html)).

Additionally, I want to inform you that many well-known antiviruses swear at the installer ([link to VirusTotal](https://www.virustotal.com/gui/file/a53f263f27421be64c023441492cc84da2cb43eeac1472b80763db347d7e4151/detection)), but at the same time everyone considers the main executable file to be safe. This can be a problem, so you should consider solving this problem.

**Comment by DavidXanatos** [comment]
This to be fixed requires a few 1000€ for an EV Code signing certificate.

I for myself consider that a waste of money only to keep some lazy antivirus fools happy.

Besides some antiviruses even complain about the properly signed processhacker driver, so I consider this issue non resolvable.

Eider you control your antivirus in which case you can tell it to allow the file or it controls you.

**Comment by mrkaban** [comment]
I was mistaken, the portable version does not solve the problem.

Anyway, thanks for the program! And I beg you to periodically think about how to solve this problem.

and if you raise money through kickstarter? DiskCryptor is generally a legend.

**Comment by DavidXanatos** [comment]
I have compared the virus total for the TE version 1.1 and 1.2
the 1.1 and prior releases look all mostly fine.

It seams that using Inno Setup to build the installer is what makes the antivirus fools detect it.

I have re uploaded the 1.2 release with the setup packed using the custom installer tool.
Now it should be fine again.

**Comment by DavidXanatos** [comment]
mmh... A kick starter is may be really a good idea.

Ideally I would shot for the founds for a EV certificate and a LLC to attache it to as attaching it to a person is probably not the smartest thing in the world.

**Comment by mrkaban** [comment]
Updated the link on my site, thanks!

If you create a project on the kick starter, write, I will also throw off a little money.

**Comment by DavidXanatos** [comment]
There is a pay-pal donation option on the https://www.diskcryptor.org/ page so you don't need to wait until a kick starter.

**Comment by mrkaban** [comment]
Stupid paypal does not support credit cards from Russia.
