### ISSUE TITLE
qwt.dll not into the zipfile !!

### ISSUE THREAD

**Issue by blackcrack** [taskexplorer/TaskExplorer#14]
Hi,

in the actual Release is not the qwt.dll by side of the binarys.. you should check it...
win7

best regards
Blacky

blackysgate.de

**Comment by DavidXanatos** [comment]
> 
> 
> Please note that this release contains only the main binaries and files from the 1.2.5 are required.
>

**Comment by blackcrack** [comment]
oh ah.. well.. i have it nowhere read, there is only in any description "new Version" and nothing from
"you have use the old files from the version before"
The release should repacked and fully functional or the users be disappointed and let this program left and kick it in the trash and the first touch is for the a.....

this was for me a first touch.. but i have 20 years computers behind me ..

**Comment by DavidXanatos** [comment]
Well its clearly marked as a prerelease, an he actual production release is 1.2.5

**Comment by blackcrack** [comment]
@DavidXanatos 

and, what helps if on majorgeeks upload as full version,
there helps also not " i have it maked.." the users see, there is a fail on it and kicks it on the trash.. this is not a full programs and is a patch for the program before.. but well.. it's your's.. 

https://www.majorgeeks.com/files/details/task_explorer.html

and other freeware and opensource News portals make the same mistake..news .. 
i be one of the Members of some Portals efb.nu in short and the first reaction was.. "oh bullschit.. a crap program.. kick in the trash" up to i have look more about and have give you the issue..

best

**Comment by DavidXanatos** [comment]
I did not realize a professional sie would make such a mistake,
I will rectify it asap,
thanks for the heads up.

**Comment by blackcrack** [comment]
@DavidXanatos "Sie" ? quatscht Du Deutsch ? :smiley:

**Comment by DavidXanatos** [comment]
Jawol!

**Comment by blackcrack** [comment]
was , du bisch rechts ? und auserdem, das sollten 2 L sein ;)

**Comment by DavidXanatos** [comment]
Nein, ich bin ein nerd :D

**Comment by blackcrack** [comment]
*g* Sind wir das nich alle ? *g*
so mal nebenher, dein proggy iss nichmal soo sclecht aufgebaut..
kennst Du den "System Explorer" ?
