### ISSUE TITLE
Restoring fullscreen app

### ISSUE THREAD

**Issue by youurayy** [taskexplorer/TaskExplorer#3]
1. make the app maximized
2. click the Close [X] button (app will hide in Windows taskbar)
3. double click the app icon in the Windows taskbar
4. the app opens in a maximized window, but the content of the app is not stretched to the full window size, i.e.:

![image](https://user-images.githubusercontent.com/588573/62161710-7af8e200-b31f-11e9-841e-a07c52904f03.png)

**Comment by youurayy** [comment]
Additionally, minimizing and restoring a non-fullscreen app resizes the app window back to a default size.

**Comment by DavidXanatos** [comment]
does that still happens to you with version 0.6?
i tryed to reproduce the issue as described but it did nto happen for me.

**Comment by UnlimitedChild** [comment]
I have the same problem now. I use the latest build ...

**Comment by DavidXanatos** [comment]
I know I will have to fix that...

**Comment by DavidXanatos** [comment]
I think i found out what the issue was, it will be fixed in build 1.2
